# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18813bd3a078f0539e288d2ee99d1817c4e12cdd8d2f502d0dd5fe35a816c1b5df49664cc12e4f81b8db3558480fdb467d6c570f2b6587678cd00924d3a5d667

test:
  secret_key_base: e282f1c8cf970dfad44d5dc305ab0b3157ec3db99743b3bd4d45a509c7448de3cffa797700a020319fc5dbd0d5e7957729ed2c340acdd32f28f875c28f4fed25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
